{{- if not .Values.vaultwarden.enabled }}
{{- if and (not .Values.vaultwardenRsaPublicKey.existingSecret) .Values.vaultwardenRsaPublicKey.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden-masterless.vwRsaSecretName" . }}
  labels:
    {{- include "vaultwarden-masterless.labels" . | nindent 4 }}
type: Opaque
stringData:
  rsa_key.pub.pem: |
    {{- .Values.vaultwardenRsaPublicKey.publicKey | nindent 4 }}
{{- end }}
{{- end }}
